name: tokyo_roulette_predicciones
description: Herramienta educativa de análisis estadístico y simulación de sistemas RNG. Propósito exclusivamente educativo, no para gambling real.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^10.0.0  # Para cobros Stripe
  in_app_purchase: ^3.2.0  # Soporte in-app
  firebase_core: ^2.24.2  # Firebase base
  firebase_remote_config: ^4.3.12  # Para updates dinámicos cada 4 meses
  cloud_firestore: ^4.15.3  # Almacenar emails
  firebase_auth: ^4.16.0  # Auth para emails
  intl: ^0.18.1  # Idioma/país
  device_info_plus: ^9.1.2  # Info dispositivo/plataforma
  url_launcher: ^6.2.4  # Comentarios via email
  shared_preferences: ^2.2.2  # Storage local
  charts_flutter: ^0.12.0  # Gráficos
  firebase_messaging: ^14.7.10  # Notificaciones para invitaciones
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/